language: node_js

node_js:
  - "7"
  - "8"

install:
  - npm install -g truffle
  - npm install

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always